---
- name: Create GCP Service Account 
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: check if the service account exist. 
      gcp_iam_service_account_info:
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
      register: serviceaccountinfo

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: "{{ item.email }}"
      loop: "{{ serviceaccountinfo.resources }}"
    
    - name: create a service account
      google.cloud.gcp_iam_service_account:
        name: "{{ gcp_serviceaccount_name }}"
        display_name: My Ansible test key
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      loop: "{{ serviceaccountinfo.resources }}"
      when: item.email.find(gcp_serviceaccount_name) == 1
    

   
