---
- name: Create GCP Service Account 
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: check if the service account exist. 
      gcp_iam_service_account_info:
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
      register: serviceaccountinfo

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: serviceaccountinfo
      when: '"aapongcp-th01-sa" in serviceaccountinfo'
    
    - name: create a service account
      google.cloud.gcp_iam_service_account:
        name: sa-{{ resource_name.split("-")[-1] }}@graphite-playground.google.com.iam.gserviceaccount.com
        display_name: My Ansible test key
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
    

   
